### ISSUE TITLE
Addon not enabling, icons wrong alignment

### ISSUE THREAD

**Issue by figueira-israel** [Baertram/ResearchAssistant#4]
Great addon, good job, there is a small issue for me that the addon doesnt start working until I open the addon settings page, Im using it with the account wide option disabled, also sometimes the icons go to the left over the item name instead of being in the middle

**Comment by Baertram** [comment]
Hello @figueira-israel , 

I'm not experiencing this "icon miss placement". Could you please disable all other addons and test if withonly RA enabled the icons are placed correctly.
Maybe it's an issue due to other addons active the same time.

About the addon not working until you open the settings menu:
The same here, please test if this is reproducable with only RA enabled!
If not you need to find out locally on your side which other addon is interfering here, as you could run dozens of other addons and your settings at these addons is something I cannot know/see ;) Thanks for your understanding that I can only help if the errors are reproducable with other addons disabled. If you find out more, or which addon causes this, we can have a look at it.

Are the icons missing at the inventory rows until you open the settings menu or what do you mean by "doesn't start working"?
Or what is not working then?

Many thanks for your feedback.

**Comment by Baertram** [comment]
No feedback by user since years, closed
