### ISSUE TITLE
Feature request: Gamepad & accessibility mode support

### ISSUE THREAD

**Issue by Misza13** [Baertram/ResearchAssistant#7]
As a user of your addon, I'd like to be able to use it while in gamepad & accessibility mode, so I can use it comfortably on my Steam Deck.

I'm creating this as a tracking issue/feature request.

If I were to actually dig my teeth into Lua and ESO addon scripting, would you be willing to accept a PR for this? Or should I create a separate addon?

**Comment by Baertram** [comment]
Hi I'd say create a new addon for that please. Or checkif there is already something out there by IsJustaGhost maybe?
He creates GP mode addons or UI additions.
Serch for author IsJustaGhost on www.esoui.com -> Addons search

GP mode is totally different from keyboard (in control names, code, lua functions to use etc.) so there never is a simply "conversion" possible :-(

I do not play in gamepad mode so I do not even know how to test and check how it normally/ususally works.
I personally won't work on GP support because of the before mentioned points. If ZOs woudl have build i more easily to convert or support I would be up for it but it's like creating a totally new addon in most cases and I do not have the time, nor the will to start that, cuz it also will open the work to do at each patch again, which I'm currently already strugglign with more than 100+ addons and libraries of myself, which I took over and try to keep alive.

Thanks for your understanding.
